### ISSUE TITLE
[NFTScan Pro API] 

### ISSUE THREAD

**Issue by sznariOsmosis** [rebase-network/benefits#4]
### 申请人

史志强

### NFTScan API 注册邮箱

1967363466@qq.com

### 联系方式

1967363466

### 申请理由

NFT数据分析

**Comment by nftscan2022** [comment]
亲爱的开发者你好：
账户1967363466@qq.com已开放Pro权限，每日请求上限：30000次，时长：3个月，使用中遇到任何问题请通过NFTScan官网底部社交平台联系我们。https://www.nftscan.com
