### ISSUE TITLE
[BlockPI Services] 

### ISSUE THREAD

**Issue by syslink** [rebase-network/benefits#5]
### 申请人

Sam

### BlockPI Network 账户

yusingle001

### 联系方式

CryptoMan#0780

### 申请理由

我的项目需要一个实时性比较好的节点，可以快速获取当前的合约事件、交易数据等信息，然后根据用户设置好的脚本自动执行一些任务，目前想要支持尽可能多的EVM链

**Comment by CloverRL** [comment]
您好，我们并未查找到您提供的账户信息对应的账户，请提供您用于登录的BlockPI Network注册邮箱或钱包地址或者UID，我们会将对应的用量赠送至您的BlockPI账户中。

**Comment by syslink** [comment]
UID: kIqx7IPnDQUJ
thx

**Comment by CloverRL** [comment]
您好。
一个包含5亿RU的package已经发至提供的账户。后续有任何使用上的问题或是更多需求也可以通过Discord 联系我们！
谢谢~

**Comment by syslink** [comment]
收到，非常感谢
